version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: RMM_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: slatermm
    ports:
      - "5432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../dashboard:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

  checkmk:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        AUTOMATION_SECRET: ${AUTOMATION_SECRET}
    ports:
      - "5000:5000"
      - "8000:8000"
    environment:
      - CMK_PASSWORD=slatermm
      - CMK_SITE_ID=main
    volumes:
      - checkmk-data:/opt/omd/sites
    env_file:
      - .env

volumes:
  postgres-data:
  checkmk-data: