version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: RMM_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: slatermm
    ports:
      - "5432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../dashboard:/usr/share/nginx/html

#   influxdb:
#     image: influxdb:2.0
#     ports:
#       - "8086:8086"
#     environment:
#       - DOCKER_INFLUXDB_INIT_MODE=setup
#       - DOCKER_INFLUXDB_INIT_USERNAME=admin  # Customize as needed
#       - DOCKER_INFLUXDB_INIT_PASSWORD=slatermm  # Your chosen password
#       - DOCKER_INFLUXDB_INIT_ORG=myorg  # Customize as needed
#       - DOCKER_INFLUXDB_INIT_BUCKET=metrics_db  # Initial bucket name
#       - DOCKER_INFLUXDB_INIT_RETENTION=1w  # Retention policy, customize as needed
#       - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=myadmintoken  # A token you'll use for admin operations
#     volumes:
#       - influxdb-data:/var/lib/influxdb2

volumes:
  postgres-data:
#   influxdb-data: