version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: RMM_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: slatermm
    ports:
      - "5432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ../dashboard:/usr/share/nginx/html
  #     - ./default.conf:/etc/nginx/conf.d/default.conf

  checkmk:
    image: checkmk/check-mk-raw:latest
    ports:
      - "5000:5000"
      - "8000:8000"
    volumes:
      - checkmk-data:/opt/omd/sites

volumes:
  postgres-data:
  checkmk-data:
